apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "testdemo"
  description: "demo"
  annotations:
    github.com/project-slug: leemills83/testdemo
    backstage.io/techdocs-ref: url:https://github.com/leemills83/testdemo
spec:
  type: website
  lifecycle: experimental
  owner: "leemills"
